### ISSUE TITLE
Investigate seed data error

### ISSUE THREAD

**Issue by mhelmetag** [exercism/seeds#10]
Possibly remove `comment_threads` and `comment_threads_id_seq` tables to suppress this error when running `bin/setup`:

```
psql:db/seeds.sql:138: ERROR:  relation "comment_threads" does not exist
psql:db/seeds.sql:139: invalid command \.
psql:db/seeds.sql:146: ERROR:  relation "comment_threads_id_seq" does not exist
LINE 1: SELECT pg_catalog.setval('comment_threads_id_seq', 1, false)...
```

**Comment by kytrinyx** [comment]
oh. Oops. I've been changing a bunch of things in the database lately without checking in with the seeds... this is totally my fault.

Let me debug. It might just need to be regenerated off of the current database structure.

**Comment by mhelmetag** [comment]
No worries! Didn't mean to raise any alarms. Wasn't like a fatal error or anything. Just wanted to point it out :)

**Comment by kytrinyx** [comment]
no, it's great! If nobody points it out then it's unlikely to ever get fixed :)

**Comment by kytrinyx** [comment]
OK, I think that should do it. Would you mind trying to pull down new seeds and see if that works for you?

**Comment by mhelmetag** [comment]
```
psql:db/seeds.sql:1613: ERROR:  relation "conversation_notifications" does not exist
psql:db/seeds.sql:1614: invalid command \.
psql:db/seeds.sql:1621: ERROR:  relation "conversation_notifications_id_seq" does not exist
LINE 1: SELECT pg_catalog.setval('conversation_notifications_id_seq'...
```

**Comment by kytrinyx** [comment]
Oh, uhm. Let me try that again!

**Comment by kytrinyx** [comment]
Ok, pushing it up again.

**Comment by mhelmetag** [comment]
All clear! Thanks :+1:
