### ISSUE TITLE
Regenerate seed data with non-null timestamps

### ISSUE THREAD

**Issue by amar47shah** [exercism/seeds#6]
While seeding my development database with `rake db:seed`, I received this error:

````
psql:db/seeds.sql:1511: ERROR:  null value in column "created_at" violates not-null constraint
DETAIL:  Failing row contains (1, 1, joined, null, null, null).
CONTEXT:  COPY lifecycle_events, line 1: "1	1	joined	\N	\N	\N"
````
(This was the only error.)

Looking into it, I found that non-null constraints for timestamps were added [recently](https://github.com/exercism/exercism.io/pull/2370) to fix a Rails 4 deprecation warning.

Probably not high priority, but it would be nice to have valid data in `lifecycle_events` to go with the rest of the seeds. Thanks!

**Comment by kytrinyx** [comment]
Oh, cool. Yeah, I'll see about updating this. Shouldn't be too hard, but the seed data can be a bit fiddly since I don't touch it very often.

**Comment by amar47shah** [comment]
Thanks!

**Comment by kytrinyx** [comment]
If you have a chance to try it out, let me know if it works for you.

**Comment by amar47shah** [comment]
Worked like a charm :)
````
➜  exercism.io git:(master) ✗ rake db:seeds:fetch
fetching over the wire
➜  exercism.io git:(master) ✗ rake db:reset      
➜  exercism.io git:(master) ✗ rake db:migrate    
...
➜  exercism.io git:(master) ✗ rake db:seed       
...
➜  exercism.io git:(master) ✗ bin/console
[1] pry(main)> LifecycleEvent.count
=> 208
````

**Comment by kytrinyx** [comment]
Sweet, thanks for checking!
